### ISSUE TITLE
Question: How to allow Base (first) tenant to be accessible by all other tenants

### ISSUE THREAD

**Issue by nigel-dewar** [joeaudette/cloudscribe#132] opened 2017-03-21 00:07 UTC
Hi Joe,

This question comes after considering your last response back, about creating a filter to allow users from some tenants to access tenants from others.

This question comes from 2 use cases that have popped up for myself over the last couple of weeks. Which leads me to be believe the use case could be quite common.

In allot of multi-tenant sites, there is often a base tenant. And this is the case with your cloudscribe system.
Now often the case is that you wish all users of individual tenants completely isolated, but.... you wish for them to ALL be able to access a base tenant. 

Think the case of some protected wiki which all of your customers whom have a tenant, should be able to access. Now you require ALL users to have an account, and ALL to access the base tenant where the wiki lives, however that does not allow users from one tenant to get into another.

Is there a way this use case could be built into your framework? Because I believe it to be a valid case that is common enough to warrant its inclusion.

To add further to this please consider the following  scenario which would use this use case.

Scenario 1: Real Estate site:
 Say you had a real estate site which provides house listings to buyers, sellers and agents.

You have 2 types of users.
private sellers
real estate agents.

Private sellers create an account on the base tenant. They are an individual so no need for a tenant.
Agency (real estate agents) create a tenant, add their staff members. 

Both types of users can access the base tenant, but... only agent users can access the agency tenant. 

I am looking through cloudscribe source and trying to figure out where best to mod to fit this need.
I'm looking at the controllers located under cloudscribe.Core.Web, things like the AccountController.

The other place I'm looking at is further up the chain. But it is hard to determine where exactly I should make changes.

If you could shed some light in any particular areas I should focus on to make the changes, or things to watch out for that would be greatly appreciated. Or If I'm trying to do something which is just not possible then please just say so.

Kind Regards

Nige

**Comment by nigel-dewar** [comment] 2017-03-21 00:31
One other thing, looking through your code. Damn You're good mate! This is some seriously high quality stuff Joe. The more I am looking at your kit, the more I am appreciating all the work you have done and the challenges you have solved. Thank you.

**Comment by nigel-dewar** [comment] 2017-03-21 04:24
After spending almost a day on this, I'm lost. I see what you mean by 'all or nothing'.

**Comment by joeaudette** [comment] 2017-03-21 12:23
Getting security right is difficult, there are a lot of things to understand. My goal is to make sure security isolation between tenants works as intended. 

The issues do vary by scenario, ie mvc tenants use cookie auth and with cookie auth we get cookie isolation by default for different domain/host names because the web browser keeps cookie separated by domain/host. For folder tenants we don't get cookie isolation from the browser because the tenants share the same domain/host name. So extra steps are needed in that case to make sure each tenant uses different cookie names and different authentication scheme names and we also have code to reject the principal if there is not a correct claim for the tenant id.

spa scenarios typically use jwt instead of cookie but for apis running in the same installation as the main cloudscribe core cookies will also work ie if the user has a cookie with correct roles/claims the authorization middleware will accept it just as it would accept a valid jwt. To be sure of only using jwt it is best if the spa is not part of the main cloudscribe core site but a remote app. However a spa running in the same context as the main cloudscribe app can also use mvc view to get initial state and tenant specific configuration into the spa, so there are trade offs.

So with all of that said, I think it is not a good idea to try to code in any exceptions that allow access to the base tenant for users from other tenants. If anything the base tenant should be kept more secure because it is the tenant that can create other tenants. Adding complex rules and loopholes to rules in security is best avoided.

What I would suggest if you you want users who register in one tenant to be able to also login to another tenant (but without using related sites mode) then the user account should be copied to the other tenant. You could implement and inject [IHandleUserCreated](https://github.com/joeaudette/cloudscribe/tree/master/src/cloudscribe.Core.Models/EventHandlers) which provides an event hook for when a user is created and from there you could have custom code to decide if the user account should be copied to any other tenants and do so if needed. There might be other issues to solve if you want to keep password changes in sync across those tenants, maybe a db trigger or something could be done for that.

**Comment by nigel-dewar** [comment] 2017-03-21 12:42
Thanks Joe. After some thought today i understand. Thanks for the heads up on the differences between how cookies are handled in folder mode vs domain mode. I would not have learnt that had you not said so.

i agree about what you say with embedded Spa. It really is a tradeoff. I spent a little time thinking about using the existing cookie and nothing wrong with that. Cheers.

**Comment by nigel-dewar** [comment] 2017-03-21 21:56
Security is very difficult to understand. That is why your work is very important. Ive only been involved in programming for about 3 years now.

Here has been my experience. I found learning the basics pretty 'basic'. Thinga like html,css and project structure were straight forward. Things like Javascript and frameworks were a little more of a challenge but not too hard. I found serverside stuff c#, asp.net, entity framework again straight forward.

But everytime security has tripped me up. And it has been hard becuase often what customers are asking for revolves around a really good understanding of it. 

There are so many different ways to do it, so many different tools and things to know. 

I think the identityserver4 integration is really good. I love you and the identityserver guys are leveraging asp.net core identity becuase at least it provides folks with some kind of common base to study. What i mean is the documentation for asp.net identity is quite plentiful so you get some help there.

Im not young, but i started programming i believe where alot of young folk are starting now which is frontend dev. Ya start with all these awesome frontend tools and frameworks and then as soon as you want to do anything complex that involves identity you get tripped up. Especially the case with anything that involves multitenant.

There seems to be no real standard for this. And this makes it especially challenging to learn. I was suprised to find how scant the internet is on good quality knowledge for multitenant. I did of course find saaskit which looks great, and i beleive you leverage this, is this right? But i did not find anything that showed how to dynamically create tenants like what cloudscribe does. I have no idea how to wire up dns domain stuff automatically so as to have domain mutiltenant, so the way you do it with folder base separation really works for me, and most likely for many folk.

i will have a good look into the differences between having an embeddes SPA use the mvc cookie and then using jwt with oidc-client.

The reason i thought oidc-client was needed even in an embedded spa was for the refresh aspect. For instance. Say your customer had spa window open and then goes into a meeting for 2 hours. When they come back they start clicking around and bad stuff happens (401 unauthorized) as the spa tries to communicate to the api. Now if it were an mvc page pure then this would not happen becuase there would be a post back on just about every action in which case the expired auth (if they were expired) would simply be refreshed. But in a spa sitauation i dont think this would be the case. The user starts clicking, the spa tries to talk to API , gets 401. Now one could deal with that by then redirecting user to an mvc page again which has Authorized attribute on it, and then a cookie refresh will happen. So it may be really simple. I dont know until i try and see.

Having the spa use the mvc cookie when embedded does simplify things as then u dont have to go setup the jsclient in admin on the new tenant when you create it. So if there is a way i can make this work nice, i will definitely go down this road.

otherwise, ill just embed the spa using oidc-client and figure out a way to automatically setup jsclient on that new tenant on tenant creation.

**Comment by nigel-dewar** [comment] 2017-03-21 23:59
Hi Joe,

The fix for the roles works great thanks! 

Was looking at the DB and wondering if the following would be possible.

![image](https://cloud.githubusercontent.com/assets/9402456/24175785/df491064-0ee3-11e7-8156-bbc0d5cd90a9.png)

I was thinking if a join table was put in place where a single user could belong 1 or many tenants, then it might be possible to achieve 'single user' sharing across multiple tenants. Its just an idea, I will give it a shot.

In this case I would mod the User model. The user would reference a UserSites table. And then I will need to modify the queries so that when fetching a user, I look into the UserSites table to check that this user trying to sign in has that Site relationship. If they do then I'll let them through.

That way I think it wont break any of your existing logic/work around ensuring the authentication is isolated against that tenant.

Now I understand that the user would still need to signin to every tenant. That is fine. One must do the same in almost every other multi-tenant system I've seen. Otherwise it wouldn't be multi-tenant right.

I can see things from your perspective. As you have stated you are providing a base starterkit for multitenancy. One cannot account for every little edge case that every tom dick and harry come up with.

But I am wondering if I made the following changes, can you see any reason why it would not work?

This would then negate the need for a copying mechanism for users from one tenant to another. A single user ''email account" would be all one would require for 1 or more tenants (sites).

Sorry to be such a pain. I'm pretty determined to see if this use case is achievable as I feel it would pop up enough (has for me) to warrant figuring it out.

**Comment by joeaudette** [comment] 2017-03-21 23:59
I think for spa samples in the StarterKits it is best to use jwt. Main thing I was trying to point out is if the spa page runs in the same site as the oidc server it shares cookies and if you were logged into the mvc site then the spa will share the cookie and the browser will pass it in the headers of every request and it may satisfy requirements of the authorization middleware independently of what may also be sent in a jwt token from the spa. So when testing the spa it is best to not be logged into the mvc site in the same browser.

Not saying it is wrong to ever use cookie instead of jwt in a spa, it can be easier than jwt but if you build a spa and use jwt then it is easier to make a cordova app which you can't do with cookie auth.

I think cookies tend to get configured with longer life span than jwt in typical use auth cookies will last as long as the browser is not closed or can auto refresh from the middleware without the client getting a 401, it would just be refreshed seamlessly depending on configuration. They can be tightened down of course but in mvc that would add the whole redirect login experience more frequently which people don't enjoy. The default behavior in the starterkits is cookies last the lifetime of the browser session and maybe beyond that if remember me is checked in the login screen.

So I think if you know a specific project is never going to be converted to apps with cordova and most of your users normally login to the mvc site already and you want to host some spa apps in the same site it might be much easier to just use the same cookie auth for the spa apps built to run there.

But if you want the spa apps hosted remotely or an easier path towards a cordova app, it is better to stick with jwt.

I wrote a wrapper polymer web component that wraps the oidclient js in the idioms of polymer web components to make it easier to be consumed in a ploymer style app. Would be great if we could make samples for angular and react. I don't know either of those but am interested in learning react so would love to see a sample of that myself. If you have knowledge of those and could help with samples for either of those it would be awesome!

ultimately on the server side we protect things by decorating controller actions with an Authorize attribute and a named policy. The policy with the given name must be defined in Startup of the app or it will error out. The policy can define the requirements of roles and or claims or other things but mainly roles and claims is what I would use. 

In cookie auth the users roles and claims are encrypted in the auth cookie and passed with each request and processed into a claims principal by the cookie auth middleware. In jwt auth the jwt token is passed with each request and processed by the jwt auth middleware. If both are running I "think" they just get merged into the same claimsprincipal. So if you do test jwt spa that are running in the same site as the mvc just be aware of that and log out of the cookie when testing.

**Comment by joeaudette** [comment] 2017-03-22 00:14
I think your proposed changes would work and require probably many more changes and complexity in other places. ie can admin of any tenant modify the user? we have to add joins in lots of other places to show the user in the user list. I just don't think I want to go there right now. It is a lot to consider how many scenarios I want to be on the hook for supporting, I will be here for a long time providing support for this project and I have to think carefully about adding complexity and scope creep to more scenarios.

If you don't like the copy user idea then think in terms of how to build what you need externally. ie maybe there are methods that could be made as virtual to allow you to override behavior in a sub class. maybe there are places in implementation where you want to change code but if we can make an interface where you can plugin custom logic while keeping the current logic as the default implementation of the interface.

**Comment by nigel-dewar** [comment] 2017-03-22 00:42
Hi Joe thanks for your reply so quick on this.

Yes totally understand. You are getting this thing ready for .NET foundation right so you need to have  defined scope. 

I will do the work on my side privately and submit to my github repo for you to look at. As you said there would be many changes and additional join tables etc required to achieve what I am looking at. Thats alot of overhead and potential trouble and you dont want that.

What I can try to do if I get it right (and thats an if and will take some time), then I can likely produce it as a nuget add-on and maybe that might be a good pattern for anyone looking to extend your base product. Thoughts? I guess I would just have to ensure that when the DB migrations run they dont much up a site owners data, and secondly there would need to be effective backout scripts. I'll have to ensure I get this right If anything. I'd say ensuring that the site owners DB is backed automatically before any changes is a no brainer.

As far as the SPA stuff goes, yeah its one of those situations where Pros and Cons exist which has a person going to and for, to use existing MVC cookie or not to use existing MVC cookie. It really depends on the site owners needs right. 

I have an Angular SPA with oidc-client wrapped in an an angular module. I can't take credit for the work, I found this in a guys cordova (Ionic) repo, and it works well.

The oidc-client.js works fine even with a SPA embedded in an MVC page, so now really it just becomes a case of should I do it or not.

The work I need to do around supporting a cordova client makes me pro- jwt setup vs cookie. The reason I say this is, If I want to support cordova then I will want to do the work of automatically setting up the cordova (js) client in the tenant at tenant creation time. If I'm going to do this work, I might as well stick with the JWT setup even if Im just embedding the SPA in MVC, because then when one goes to build their cordova app, they dont have to worry about changing out the auth logic in the app for cookie to JWT, it will already be done for them. They just need to reference the doco for the SPA app, and they good to go.  The Advantages I see of embedded SPA as stated is the automatic setup. I mean automatic as in the MVC page feeding into the SPA all the things it needs, like the authority, callback, silentfresh location etc. This certainly is handy that your cloudscribe creates all this including the tenant folder URL.

If I go the route of setting up seperate SPA outside of MVC, then I dont get the automatic folder url setup. sooo, in this case like the cordova app, the user would be required at least on first time use, to enter their tenant URL, so the SPA could go get the config info and set itself up. This maybe is no real issue.

In the case where I am talking about having a single user table with a 1 to many relationship to tenants (the user account having a base tenant site guid), then what could happen is the external SPA loads up (SPA has default url like "www.spa.com"), and user logs in. When they initiate login, their user account is looked up and they are presented with an inbetween page which asks which particular tenant they wish to log into, when they select the tenant the rest is history and they get logged in as that tenant. Sounds like a lot of work. Probably is. 

Again with the SPA, Id say It would make sense to produce this is a nuget extention to your base. 

I will commit the working embedded SPA I have with Angular using angular-oidc-client.js into a repo for you to check out. So you can have a play when you get time to see how jwt goes vs cookie. I think you are right though, cookie is good and simpler.

I will get a cordova app up and running in next couple of weeks, and again commit to my repo so you can check it out, along with a React version.

Ultimately I think your base is really great. It would be insane extending the scope beyond what you already have because it already is massive. A multi-tenant starterkit is ambitious. And it would be impossible for a single guy to support every damn customization, its just too much. 

Besides nuget packages, do you see any better way of doing customization's? I feel nuget add-ons are the way to go, because then if things go wrong, the support query gets bounced through to the nuget creator. thats my thoughts anyway.

**Comment by nigel-dewar** [comment] 2017-03-22 00:47
By the way, it will take me a couple of months to fully understand what you have built. So sorry if my questions at this stage are dumb. You likely have plenty of work on and I understand if your busy and can't answer these. As I get more saavy with your base product hopefully I can contribute more meaningful queries. If you wish to get some tutorials created, let me know as I would be happy to create some. I'm not sure if github is the place for tutorials, but if you have an idea about how you would like to dispense info around cloudscribe then I'm happy to help out.

**Comment by joeaudette** [comment] 2017-03-24 18:52
yes ideal way to make your own add ons, at least if they are to be shared and re-useable, publishing nugets is what I suggest.
However, your code in your nugets should never modify tables or migrations from my nugets. your code needs to be loosley coupled, you can have your own lookup table but it should not have any foreign key on my tables.

**Comment by nigel-dewar** [comment] 2017-03-25 00:10
Ok thanks Joe, that makes sense. Cheers.


Sent from Samsung Mobile


-------- Original message --------
From: Joe Audette
Date:25/03/2017 04:52 (GMT+10:00)
To: joeaudette/cloudscribe
Cc: nigel-dewar , Author
Subject: Re: [joeaudette/cloudscribe] Question: How to allow Base (first) tenant to be accessible by all other tenants (#132)


yes ideal way to make your own add ons, at least if they are to be shared and re-useable, publishing nugets is what I suggest.
However, your code in your nugets should never modify tables or migrations from my nugets. your code needs to be loosley coupled, you can have your own lookup table but it should not have any foreign key on my tables.

**Closed** 2017-03-29 12:11 UTC
